apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: tomisebjanic/rso-payments:0.1
        name: payments
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-payments:54320/rsopayments
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://payments:8087
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 60
          periodSeconds: 3
        ports:
        - containerPort: 8087
          name: server
          protocol: TCP
        resources:
          requests:
            cpu: 150m

---

apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  type: NodePort
  ports:
  - name: server
    port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: payments

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payments
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: payments-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50